apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-lbc
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The argo CD project this application belongs to
  project: default

  source:
    chart: aws-load-balancer-controller
    repoURL: https://aws.github.io/eks-charts
    targetRevision: 3.5.0 # chart version
    helm:
      # --set
      values: |
        clusterName: roboshop-dev
        region: us-east-1
        serviceAccount:
          create: false
          name: aws-load-balancer-controller

  # Destination configuration pointing to the target cluster and namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  
  syncPolicy:
    automated:
      prune: true       # Automatically deletes resources no longer in Git
      selfHeal: true  