apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The argo CD project this application belongs to
  project: default

  source:
    repoURL: https://github.com/snraju98/roboshop-helm.git
    targetRevision: main # chart version
    path: mongodb
    helm:
      # --set
      valueFiles: 
        - values.yaml
        #- values-dev.yaml

  # Destination configuration pointing to the target cluster and namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: roboshop-dev
  
  syncPolicy:
    automated:
      prune: true       # Automatically deletes resources no longer in Git
      selfHeal: true  